image: beevelop/ionic:latest

before_script:
# Install dependencies
- npm install

cache:
  paths:
    - node_modules/
  key: "$CI_COMMIT_REF_NAME"
  untracked: true

stages:
- build

BuildTest:
  stage: build
  script:
  - ionic cordova build android
  artifacts:
    paths:
      - /builds/Sevenn/Rb6Randomizer/platforms/android/build/outputs/apk/android-debug.apk
