image: sevenn/ionic3:latest

before_script:
# Install dependencies
- npm install

cache:
  paths:
    - node_modules/
  key: "$CI_COMMIT_REF_NAME"
  untracked: true

stages:
- build

BuildTest:
  stage: build
  script:
  - ionic cordova build android
  artifacts:
    paths:
      - /builds/Sevenn/Rb6Randomizer/platforms/android/build/outputs/apk/android-debug.apk

codequality:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker pull codeclimate/codeclimate
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate init
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f json > codeclimate.json
  artifacts:
    paths: [codeclimate.json]