image: agileek/ionic-framework

before_script:
# Install dependencies
- npm install
- ionic cordova platform add android

stages:
- build

BuildTest:
  stage: build
  only:
    - master
  script:
  - ionic build android
