image: beevelop/ionic

before_script:
# Install dependencies
- npm install

stages:
- build

BuildTest:
  stage: build
  only:
    - master
  script:
  - ionic platform add android
  - ionic build android