image: shlomik/docker-ionic3

before_script:
# Install dependencies
- npm install

cache:
  paths:
    - node_modules/

stages:
- build

BuildTest:
  stage: build
  only:
    - master
  script:
  - ionic platform add android
  - ionic build android